"""Obsidian second-brain exporter — stdlib only (zero extra dependencies).

Exports the PickySteve skill registry into an Obsidian vault as one note per skill,
plus a MOC (map-of-content) index note. Confusable-pair edges from eval/skill_kg.json
are rendered as Obsidian callouts with [[wikilinks]] to the other skill's note, so the
vault's graph view visualizes the confusability graph.

Run:
  python -m pickysteve.connectors.obsidian --vault <path> [--folder PickySteve] [--stats]

Output layout (under <vault>/<folder>/):
  Skills/<Skill Name>.md   -- one note per registry skill
  PickySteve Skills.md     -- MOC index, grouped by primary tag, plus top confusable pairs

Idempotency / re-export model
------------------------------
Each note is fully OWNED and regenerated by this exporter on every run -- frontmatter,
body, and the auto-generated "## Commonly confused with" section are all rewritten from
the registry + KG on each pass, so two consecutive runs against unchanged source data
produce byte-identical files.

The ONE exception is user content: if a note contains the literal line
`%% your notes below %%`, everything from that marker onward is treated as the user's
own space and is copied through unmodified on re-export. Everything ABOVE the marker
(frontmatter, doc body, confusable-pairs section) is fully regenerated and is NOT a safe
place to leave hand edits -- they will be silently overwritten on the next run. This is
the simplest safe idempotency model available without a real diff/merge engine: the file
is owned end-to-end except for one clearly-delimited free-form zone at the bottom.

Frontmatter is hand-parsed/hand-written (a small line-based reader below) --
no pyyaml dependency. Only the flat `key: value` and `key: [a, b, c]` shapes used by
this project's registry docs and by the notes this module emits are supported.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from .. import config

MARKER = "%% your notes below %%"
OWNER_COMMENT = "<!-- pickysteve:obsidian-export -- auto-generated above the marker; edit only below it -->"

_INVALID_FS_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


# --------------------------------------------------------------------------- filenames

def safe_filename(name: str) -> str:
    """Windows-safe note basename (no extension)."""
    cleaned = _INVALID_FS_CHARS.sub("_", name).strip().rstrip(". ")
    return cleaned or "untitled"


def wikilink(name: str) -> str:
    """Wikilink that targets the note's SANITIZED filename (what's actually on disk).
    A raw name with `/` (e.g. "HTTP/Browser Caching") would otherwise be resolved by
    Obsidian as a folder path and the graph edge would break. Uses the `[[file|display]]`
    alias form when sanitization changed the name, so prose still reads naturally."""
    safe = safe_filename(name)
    return f"[[{safe}]]" if safe == name else f"[[{safe}|{name}]]"


# --------------------------------------------------------------------------- frontmatter

def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split a `---\\nkey: value\\n---\\nbody` doc into (fields, body).

    Supports the shapes this project's registry docs use: scalar `key: value` and
    inline list `key: [a, b, c]`. Good enough for our own docs -- not a general YAML parser.
    """
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end].strip("\n")
    body = text[end + 4:].lstrip("\n")
    fields: dict = {}
    for line in raw.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9_.-]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fields[key] = [v.strip() for v in inner.split(",")] if inner else []
        else:
            fields[key] = val
    return fields, body


def _yaml_scalar(v: str) -> str:
    if re.search(r'[:#\[\]{}"\'\n]', v) or v.strip() != v or v == "":
        return json.dumps(v)
    return v


def format_frontmatter(fields: dict) -> str:
    """Hand-format a flat frontmatter dict -- scalars, lists of strings, and Obsidian
    `tags:` lists (rendered one-per-line, Obsidian's preferred tag-property style)."""
    lines = ["---"]
    for key, val in fields.items():
        if isinstance(val, list):
            if not val:
                lines.append(f"{key}: []")
            else:
                lines.append(f"{key}:")
                for item in val:
                    lines.append(f"  - {_yaml_scalar(str(item))}")
        else:
            lines.append(f"{key}: {_yaml_scalar(str(val))}")
    lines.append("---")
    return "\n".join(lines)


# --------------------------------------------------------------------------- data loading

def load_registry(registry_dir: Path) -> list[dict]:
    """Return one dict per skill doc: id, name, description, tags, body (post-frontmatter)."""
    skills = []
    for path in sorted(registry_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        fields, body = parse_frontmatter(text)
        skill_id = fields.get("id") or path.stem
        name = fields.get("name") or skill_id
        tags = fields.get("tags") or []
        if isinstance(tags, str):
            tags = [tags]
        skills.append({
            "id": skill_id,
            "name": name,
            "description": fields.get("description", ""),
            "tags": tags,
            "body": body.strip("\n"),
        })
    return skills


def load_kg(kg_path: Path) -> list[dict]:
    if not kg_path.exists():
        return []
    return json.loads(kg_path.read_text(encoding="utf-8"))


def load_pick_counts(runs_path: Path) -> dict[str, int]:
    """Count how many times each skill_id appears in a line's `survivors` list."""
    counts: dict[str, int] = {}
    if not runs_path.exists():
        return counts
    with runs_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            for sid in rec.get("survivors") or []:
                counts[sid] = counts.get(sid, 0) + 1
    return counts


# --------------------------------------------------------------------------- KG edges

def edges_for(skill_id: str, kg: list[dict]) -> list[tuple[dict, str]]:
    """Return (edge, other_side) pairs touching skill_id. other_side is 'a' or 'b' --
    the side skill_id is NOT on -- i.e. the side describing the OTHER skill."""
    out = []
    for edge in kg:
        if edge["a"] == skill_id:
            out.append((edge, "b"))
        elif edge["b"] == skill_id:
            out.append((edge, "a"))
    return out


def confused_section(skill_id: str, kg: list[dict], id_to_name: dict[str, str]) -> str:
    edges = edges_for(skill_id, kg)
    if not edges:
        return ""
    parts = ["## Commonly confused with"]
    for edge, other_side in sorted(edges, key=lambda e: -e[0]["sim"]):
        other_id = edge[other_side]
        this_side = "a" if other_side == "b" else "b"
        other_name = id_to_name.get(other_id, other_id)
        this_signal = edge[f"{this_side}_signal"]
        other_signal = edge[f"{other_side}_signal"]
        parts.append(
            f"> [!warning] vs {wikilink(other_name)} (similarity {edge['sim']:.2f})\n"
            f"> {edge['distinguisher']}\n"
            f"> **Pick this one when:** {this_signal}\n"
            f"> **Pick {wikilink(other_name)} when:** {other_signal}"
        )
    return "\n\n".join(parts)


# --------------------------------------------------------------------------- note rendering

def render_note(skill: dict, kg: list[dict], id_to_name: dict[str, str],
                 picks: dict[str, int] | None, preserved_tail: str | None) -> str:
    fields = {
        "id": skill["id"],
        "description": skill["description"],
        "tags": skill["tags"],
        "aliases": [skill["id"]],
        "source": "pickysteve",
    }
    if picks is not None:
        fields["picks"] = picks.get(skill["id"], 0)

    parts = [OWNER_COMMENT, "", format_frontmatter(fields), "", skill["body"].strip()]

    section = confused_section(skill["id"], kg, id_to_name)
    if section:
        parts += ["", section]

    if preserved_tail is not None:
        parts += ["", MARKER, preserved_tail]

    return "\n".join(parts).rstrip("\n") + "\n"


def extract_preserved_tail(existing_path: Path) -> str | None:
    if not existing_path.exists():
        return None
    text = existing_path.read_text(encoding="utf-8")
    idx = text.find(MARKER)
    if idx == -1:
        return None
    tail = text[idx + len(MARKER):]
    return tail.lstrip("\n")


# --------------------------------------------------------------------------- MOC

def primary_tag(skill: dict) -> str:
    return skill["tags"][0] if skill["tags"] else "untagged"


def render_moc(skills: list[dict], kg: list[dict], id_to_name: dict[str, str],
               picks: dict[str, int] | None) -> str:
    lines = [OWNER_COMMENT, "", "# PickySteve Skills", "",
              f"Auto-generated index of the PickySteve skill registry, exported for browsing "
              f"and confusability-graph exploration in Obsidian.", "",
              f"**{len(skills)} skills** indexed.", ""]

    groups: dict[str, list[dict]] = {}
    for s in skills:
        groups.setdefault(primary_tag(s), []).append(s)

    for tag in sorted(groups):
        lines.append(f"## {tag}")
        lines.append("")
        for s in sorted(groups[tag], key=lambda x: x["name"]):
            lines.append(f"- {wikilink(s['name'])} -- {s['description']}")
        lines.append("")

    if kg:
        lines.append("## Most confusable pairs")
        lines.append("")
        top = sorted(kg, key=lambda e: -e["sim"])[:10]
        for edge in top:
            a_name = id_to_name.get(edge["a"], edge["a"])
            b_name = id_to_name.get(edge["b"], edge["b"])
            lines.append(f"- {wikilink(a_name)} vs {wikilink(b_name)} -- similarity {edge['sim']:.2f}")
        lines.append("")

    if picks:
        lines.append("## Most picked")
        lines.append("")
        top_picks = sorted(picks.items(), key=lambda kv: -kv[1])[:10]
        name_by_id = id_to_name
        for sid, n in top_picks:
            if n <= 0:
                continue
            lines.append(f"- {wikilink(name_by_id.get(sid, sid))} -- {n} picks")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


# --------------------------------------------------------------------------- export

def export(vault: Path, folder: str, registry_dir: Path, kg_path: Path,
           runs_path: Path, stats: bool) -> dict:
    skills = load_registry(registry_dir)
    kg = load_kg(kg_path)
    id_to_name = {s["id"]: s["name"] for s in skills}
    picks = load_pick_counts(runs_path) if stats else None

    base = vault / folder
    skills_dir = base / "Skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for skill in skills:
        note_path = skills_dir / f"{safe_filename(skill['name'])}.md"
        preserved = extract_preserved_tail(note_path)
        content = render_note(skill, kg, id_to_name, picks, preserved)
        note_path.write_text(content, encoding="utf-8", newline="\n")
        written.append(note_path)

    moc_path = base / "PickySteve Skills.md"
    moc_path.write_text(render_moc(skills, kg, id_to_name, picks), encoding="utf-8", newline="\n")

    return {"skills": len(skills), "notes": written, "moc": moc_path}


# --------------------------------------------------------------------------- CLI

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="pickysteve-obsidian")
    ap.add_argument("--vault", required=True, help="Path to the Obsidian vault root")
    ap.add_argument("--folder", default="PickySteve", help="Subfolder within the vault")
    ap.add_argument("--stats", action="store_true",
                     help="Include pick-count stats from logs/runs.jsonl")
    ap.add_argument("--registry", default=None,
                     help="Skill-doc directory (default: the production registry/)")
    ap.add_argument("--kg", default=None,
                     help="Confusable-pair KG JSON (default: eval/skill_kg.json)")
    args = ap.parse_args(argv)

    vault = Path(args.vault)
    vault.mkdir(parents=True, exist_ok=True)

    result = export(
        vault=vault,
        folder=args.folder,
        registry_dir=Path(args.registry) if args.registry else config.REGISTRY_DIR,
        kg_path=Path(args.kg) if args.kg else config.ROOT / "eval" / "skill_kg.json",
        runs_path=config.LOG_PATH,
        stats=args.stats,
    )
    print(f"[pickysteve-obsidian] wrote {result['skills']} skill notes to "
          f"{vault / args.folder / 'Skills'}", file=sys.stderr)
    print(f"[pickysteve-obsidian] wrote MOC to {result['moc']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
